blob-images:
    component: "@sls-next/serverless-component@1.18.0-alpha.27"
    inputs:
        bucketName: blob-images-frontend
        cloudfront:
            comment: ${env.NEXT_PUBLIC_BRANCH}-branch